feat: :sparkles: Ambito API connected.
nathan-hyan/cash-count-mvp pull request #6
Opened 2024-01-04 22:21 UTC by AndresEstebanGonzalez

Ambito API is now connected and show the dolar blue value. The value automatically refreshes every 5 minutes.

## Pull request type

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## If its a bug, what was the behavior?

-

Card Link: https://trello.com/c/pB0B2s3J

## What is the new behavior?

App is now able to fetch the dolar value using the Ambito API.

## Other information

-

## Preview

Paste your screenshots here! :)

2024-01-05 14:59 UTC, nathan-hyan reviewed
Amazing work, some comments!

2024-01-05 14:59 UTC, nathan-hyan commented on src/components/Navbar.tsx
> +  });
Move this logic to a custom hook.

2024-01-05 14:59 UTC, nathan-hyan commented on src/components/Navbar.tsx
> +  const DOLAR_REFETCH_INTERVAL = 300000;
Move this constant to constants.ts

2024-01-05 14:59 UTC, nathan-hyan commented on src/components/Navbar.tsx
> +    const response = await fetch('https://mercados.ambito.com/home/general3');
Don't ever hardcode api urls. Move the url to an .env file

2024-01-05 14:59 UTC, nathan-hyan commented on src/components/Navbar.tsx
> +  const DOLAR_INFORMAL = data[1].venta;
Export this value from the custom hook itself

2024-01-09 18:05 UTC, nathan-hyan requested changes
There's a critical error in this pr, fix ASAP

Also, before you push the fix for the error, add proper types for the response of the Ambito API as specified in the next card: https://trello.com/c/pB0B2s3J

```
{
  "compra": string;
  "venta": string;
  "fecha": string;
  "class-variacion": "up" | "down" | "up-rp"
}
```

2024-01-09 18:05 UTC, nathan-hyan commented on .env
> +VITE_AMBITO_URL=https://mercados.ambito.com/home/general3
Add .env to .gitignore.

*NEVER* push .env to a repository since here's where all your secrets will be added

2024-01-11 17:28 UTC, nathan-hyan commented on src/constants/constants.ts
This constant can be inferred, no need for typing it

2024-01-11 17:33 UTC, nathan-hyan reviewed
Please check deployment messages

2024-01-11 17:33 UTC, nathan-hyan commented on src/hooks/useFetchDolarValue.tsx
> +    return <div>Loading...</div>;
Dont return JSX in a hook.

You can do

```
let output: string

if (status === 'loading') {
    output = 'loading...'
}

if (status === 'error') {
    output = 'There was an error'
}

output = data?.[1]?.venta || 'There was an error'

return output
```

2024-01-11 17:33 UTC, nathan-hyan commented on .env
> +VITE_AMBITO_URL=https://mercados.ambito.com/home/general3
This file should not exist.

2024-01-11 17:33 UTC, nathan-hyan reviewed
Please check comments and fix asap

2024-01-11 21:23 UTC, AndresEstebanGonzalez commented on src/hooks/useFetchDolarValue.tsx
> +    return <div>Loading...</div>;
That looks so much more neater! Thanks!

2024-01-11 22:14 UTC, nathan-hyan approved these changes

2024-01-11 22:15 UTC, merged